### ISSUE TITLE
changing setModelView to onStart in sample

### ISSUE THREAD

**Issue by ninadmg** [inloop/AndroidViewModel#11]
If the setModelView() is called  inside onViewCreated(),the changes made to the View in the bindView method will be discarded when the View State is Restored. 
changing setModelView() to onStart method will solve the issue.

**Comment by Blackhex** [comment]
Although this issue is about fragments, I have some thoughts regarding Activity view-models which are relevant to this:

We are binding Activity view-models in onStart() because we need to be sure that Activity layout is already created which is not certain in onCreate() or in onPostCreate(). We are unbinding them in onDestroy() because this is hardcoded in ViewModelHelper and cannot be changed to onStop(). This has one unfortunate consequence that if you call finish() in onCreate(), the onStart() is never called and clearView() is called without corresponding onBindView() which makes problems if your are registering broadcasts in onBindView() and unregistering them in clearView() but this is quite minor issue.

Anyway, what are the reasons behind the decision that the library is designed that the view is bound/unbound in onCreate()/onDestroy() instead of onResume() / onPause() which would be better because there is no reason to be bound to view-model when view is not visible to user?
